INSERT INTO `PROBLEM` (`PROB_ID`, `DEPT_ID`, `NAME`) VALUES
(1, 1, 'Loading Problem'),
(3, 1, 'Re-Cutting Problem'),
(4, 1, 'Other Problem'),
(5, 6, 'Quality Problem'),
(6, 6, 'Wrong Trims Issued'),
(7, 6, 'Mixing Trims Problem'),
(8, 6, 'Other Problem'),
(9, 4, 'Machine Breakdown'),
(10, 4, 'Machine Settings'),
(11, 4, 'Other Problem'),
(12, 3, 'Allocated Operator Unavailable'),
(13, 3, 'Machine not available'),
(14, 3, 'Balancing Not Done'),
(15, 3, 'Other Problem'),
(2, 5, 'Cutting Quality'),
(16, 5, 'Sewing alteration'),
(17, 5, 'Quality approval'),
(18, 5, 'Other Problem'),
(19, 2, 'Operator Discipline'),
(20, 2, 'Unplanned Absenteeism'),
(21, 2, 'Other Problem'),
(22, 7, 'Operator Handling Problem'),
(23, 7, 'Skills Problem'),
(24, 7, 'Other Problem'),
(25, 8, 'No Pulling'),
(26, 8, 'Other Problem'),
(27, 9, 'No Monitoring'),
(28, 9, 'Feeding Helper Problem'),
(29, 9, 'Other Problem');